import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Kiwi_Maru } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

const kiwi_Maru = Kiwi_Maru({weight:["300","400","500"], subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestUrl = headers().get("x-url")

  return (
    <html lang="jp">
      <body className={`${kiwi_Maru.className} bg-gradient-to-b from-cyan-200  `}>
        <div className="relative">
          <div className="w-full h-full bg-white absolute -z-10"></div>
          <div className="md:hidden z-0">
            {children}
          </div>
        </div>
        
        {requestUrl &&
        <div className="">
          <iframe className="mx-auto hidden md:block w-[50vh] h-[100vh] hidden-scrollbar " src={requestUrl}></iframe>
        </div>
        }
        
        
      </body>
    </html>
  );
}
